version: '3.8'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8080"
    ports:
      - "8000:8080"
    restart: always
    env_file:
      - .env

    depends_on:
      - database

  database:
    image: postgres:14.10-alpine
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
